### ISSUE TITLE
ValueError: we only read Intel C3D files 

### ISSUE THREAD

**Issue by JKbasara** [EmbodiedCognition/py-c3d#15]
I read some c3d files successfully, but some files when I tried to read can't be read. The error is
"ValueError: we only read Intel C3D files ", how can I solve it? thx
I had a screenshot here
![default](https://user-images.githubusercontent.com/4019752/46456110-46d89180-c7e0-11e8-852e-4c087508800d.PNG)

**Comment by MengBUPT** [comment]
> I read some c3d files successfully, but some files when I tried to read can't be read. The error is
> "ValueError: we only read Intel C3D files ", how can I solve it? thx
> I had a screenshot here
> ![default](https://user-images.githubusercontent.com/4019752/46456110-46d89180-c7e0-11e8-852e-4c087508800d.PNG)

I'm having exactly the same issue with c3d files downloaded from Carneggie Mellon University. Have you solved it?

**Comment by JKbasara** [comment]
> > I read some c3d files successfully, but some files when I tried to read can't be read. The error is
> > "ValueError: we only read Intel C3D files ", how can I solve it? thx
> > I had a screenshot here
> > ![default](https://user-images.githubusercontent.com/4019752/46456110-46d89180-c7e0-11e8-852e-4c087508800d.PNG)
> 
> I'm having exactly the same issue with c3d files downloaded from Carneggie Mellon University. Have you solved it?

Yes， that's because of different CPU when generate mocap file. You can search .c3d file. If you open the .c3d file with binary editor, you will find that .c3d has many format. See that link:
https://www.c3d.org/sampledata.html
So, that python pack can only read .c3d file that under the Intel CPU system.

**Comment by lmjohns3** [comment]
I think Mattias' work will help address this issue, please feel free to re-open if needed.
