### ISSUE TITLE
Upload to newer version (climate specificly)

### ISSUE THREAD

**Issue by extraymond** [EmbodiedCognition/py-c3d#17]
Hi! I've been enjoying this library for some time, it would be nice to update this module to a newer version where argparse replaced climate. 

Since climate is not available for pypy, functionalities in scripts/ folder is unable to be launched.

**Comment by chitalian** [comment]
yes I agree. I will get on this

**Comment by chitalian** [comment]
This has actually been fixed. can we close this?

**Comment by extraymond** [comment]
Thx, it's fixed on master, but not on the  released pypi package.
Since there is similar issue #18, I will close this now.

**Comment by AKuederle** [comment]
New Pypi release is out. Please check if everything works as expected
