### ISSUE TITLE
Update the PyPi Version

### ISSUE THREAD

**Issue by kmader** [EmbodiedCognition/py-c3d#18]
The pypi version is out of date and still has the analog transpose bug (https://github.com/EmbodiedCognition/py-c3d/issues/7). It would be great to have the latest on there (or at least that bug fixed)

**Comment by AKuederle** [comment]
I second this! The current pypi version is not compatible with Python 3.9. Updating the PyPi version would much appreciated :)

**Comment by AKuederle** [comment]
@lmjohns3 Are there any news on that? I am currently considering forking the package and publish an updated version under a different name. The package is used quite regularly in our research group and more and more people are running into the py3.9 issues.

I am happy to help, if you need any assistance with that

**Comment by friggog** [comment]
@lmjohns3 any update on this?

**Comment by lmjohns3** [comment]
Hi all -- so sorry for the lack of attention on this codebase :-/ I've of course been super busy.

I think I could update the PyPI version, but it might make even more sense if anyone else was willing to take ownership of the pypi package and/or this code repo?

**Comment by AKuederle** [comment]
Hi @lmjohns3,

First of all thank you for your work on the project! I think we all fully understand that life can come into the way of open source maintenance. I would be happy to adopt the package, but I have also seen that @MattiasFredriksson has made a lot of changes and updates to the code base in the past. Maybe he might also a good candidate? Or we can share "the burden"? Happy to discuss :)

**Comment by lmjohns3** [comment]
I just noticed on PyPI that it's super-easy to add additional maintainers or owners. I'll contact you directly to arrange things.

**Comment by AKuederle** [comment]
0.4.0 is up on PyPi!

Also, Me (@AKuederle) and @friggog re now also maintainer of the project to take some of the work of @lmjohns3
