### ISSUE TITLE
KeyError: 'ANALOG'

### ISSUE THREAD

**Issue by jbg2408** [EmbodiedCognition/py-c3d#2]
I get KeyError: 'ANALOG' (line 622) when trying to use a c3d file generated from Optitrack Motion after downloading the zip file and running the set.

**Comment by lmjohns3** [comment]
Can you post a URL to the C3D file you tried to process?

**Comment by jbg2408** [comment]
I will see what I can do.  I tried to create an empty repository for it, but, from work I am not allowed to push to git
git push -u c3d master  fails with a connection issue.

**Comment by lmjohns3** [comment]
Just pushed a new version that fixes this!
