### ISSUE TITLE
latest commit breaks write function

### ISSUE THREAD

**Issue by toludwig** [EmbodiedCognition/py-c3d#24]
In c3d.py line 1070f something ugly happened, so I get a syntax error when trying to write the file.
Also, it would be great to have the custom label argument being optional.
Please update the PyPi package.

**Comment by AKuederle** [comment]
PyPi package is updated. Regarding the other issue, could you please rechek, if this still happens in the latest version of the code?

**Comment by AKuederle** [comment]
I will close the issue for now. If the issue still occurs, feel free to reopen.
