### ISSUE TITLE
How can I retrieve ORIGIN or CORNER in the FORCE_PLATFORM group ?

### ISSUE THREAD

**Issue by gonhol** [EmbodiedCognition/py-c3d#3]
Hi,

thank you for this great library. I need to get info like ORGIN or Corner which are arrays. it seems that your get_float function does not handle this. Any hint ?

Regards,

Arnaud

**Comment by lmjohns3** [comment]
You can use the ``.float_array`` property of the relevant parameter:

    r = c3d.Reader(filename)
    r.get('FORCE_PLATFORM:CORNERS').float_array

Please close if this works for you!
