### ISSUE TITLE
Reader functions outside of loop but not inside

### ISSUE THREAD

**Issue by UFNym** [EmbodiedCognition/py-c3d#30]
Reader functions perfectly well within simple function code block with paths of .c3d files as input. However, when ITERATING through list of paths of .c3d file locations, and passing those paths to the reader fails and states that: "We only read Intel 3D files (got processor 85)". The loop that the reader is failing with (but not outside of) is part of a h5py dataset creation block.

I am really struggling to find a solution. Any general insight / suggestions?

**Comment by AKuederle** [comment]
That sounds pretty strange. Are you reusing the same Reader object? I would need to check, but it might be that the Reader is statefull. Try recreating the Reader instance inside the loop.

**Comment by AKuederle** [comment]
I will close the issue for now. If the issue still occurs, feel free to reopen.
