### ISSUE TITLE
Installation is broken due to renamed c3d2csv script

### ISSUE THREAD

**Issue by AKuederle** [EmbodiedCognition/py-c3d#34]
At the moment it is not possible to install that package, because the script `scripts/c3d2csv` does not exist. The file is now named `c3d2csv.py`.

Either the `.py` extension must be removed again or the setup.py file should be adjusted.

**Comment by MattiasFredriksson** [comment]
Hey I have an updated branch where I fixed the setup script (among other things):

git clone https://github.com/MattiasFredriksson/py-c3d
cd py-c3d
python setup.py install

Only tested it on windows, and I did some changes to the api (but should be irrelevant if you are just using the c3d2csv script). Would love some feedback if you give it a try (if you experience issues on Linux I'll look into it).

BR
