### ISSUE TITLE
Does not work under python >=3.9

### ISSUE THREAD

**Issue by davidpagnon** [EmbodiedCognition/py-c3d#35]
It would be nice to update the pip version of the package :)

As it is, reader.read_frames() does not work under python >=3.9, which makes the package a tad useless.

In the pip version, _as_array uses the method fromstring which has been removed from python 3.9. 
It's been replaced by frombuffer in the github version, but you can't access it from pip (which makes it impossible to install from a requirement.txt file)

Thanks for the good work!

**Comment by AKuederle** [comment]
Pypi version is updated! Please check if your issue is resolved
