### ISSUE TITLE
Parsing valid c3d file fails 

### ISSUE THREAD

**Issue by yochaytz** [EmbodiedCognition/py-c3d#44]
[p2s1.zip](https://github.com/EmbodiedCognition/py-c3d/files/8213171/p2s1.zip)
While trying to parse this file I get 
KeyError: 'PROCESSING'
It seems that the group named PROCESSISNG appears twice in the header. Is the invalid according to the c3d format?

**Comment by AKuederle** [comment]
Could you provide the full trace back? And I am not sure, if that is valid based on the c3d format. @MattiasFredriksson Do you know if pyc3d assumes/required the group names to be unique?

**Comment by yochaytz** [comment]
I checked and it seems to be invalid, see here at page 36 "Each group name must be unique":
https://www.c3d.org/docs/C3D_User_Guide.pdf
Unfortunately in my case it seems that same group name was used with different group ids. I would try to work around that.
Full trace:
  File "/mnt/Data_Collection_syn7/GaitAnalysis/internal/ext_datasets/GPJATK/tools/py-c3d/py-c3d/c3d/c3d.py", line 1440, in __init__
    self.add_group(group_id, name, desc)
  File "/mnt/Data_Collection_syn7/GaitAnalysis/internal/ext_datasets/GPJATK/tools/py-c3d/py-c3d/c3d/c3d.py", line 1118, in add_group
    raise KeyError(name)
KeyError: 'PROCESSING'
python-BaseException

**Comment by yochaytz** [comment]
Eventually I modified add_group() such that if group name is already exist, it auto-generates different name ('PROCESSING' --> 'PROCESSING1'). Files are now readable.

**Comment by AKuederle** [comment]
Great! Could you share the modifications you made? Ideally as a merge request. Then we can discuss, if we want to add this workaround as well.
If you need any help with opening a merge request, I can help you.

**Comment by MattiasFredriksson** [comment]
Interesting case where the file contains two GROUP entries with the same name. I think supporting such cases would be good as long as a warning message is registered when it occurs as to inform users when the file does not follow the standard. It would also be good to follow a similar convention as for parameters when generating the names, namely: PROCESSING, PROCESSING2, PROCESSING3... I'm not sure every file would follow that naming convention but it would be good to stick with a similar convention as the examples in the manual (see 'Additional Parameter' section in the [manual](https://www.c3d.org/docs/C3D_User_Guide.pdf)).
