### ISSUE TITLE
Fails to read files with screen axis metadata

### ISSUE THREAD

**Issue by Peaj** [EmbodiedCognition/py-c3d#53]
When the c3d file contains screen axis metadata the file import fails with the following error:

```
Traceback (most recent call last):
  File "D:\Git\Blender\addons\io_anim_c3d\__init__.py", line 254, in execute
    msg = c3d_importer.load(self, context, filepath=path, **keywords)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Blender\addons\io_anim_c3d\c3d_importer.py", line 97, in load
    global_orient, parsed_screen_param = parser.axis_interpretation([0, 0, 1], [0, 1, 0])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Blender\addons\io_anim_c3d\c3d_parse_dictionary.py", line 189, in axis_interpretation
    O_data[:, 0] = axis_x
    ~~~~~~^^^^^^
ValueError: could not convert string to float: '+Z'
```

The `axis_interpretation` method expects get_screen_axis to return vectors but get_screen_axis and set_screen_axis read and write the axis in string representation ("+Z", "-Y", etc.)

I am writing an exporter and used set_screen_axis to write the axis data to the file.
When reimporting the file I encountered this error.

**Comment by LeyangWen** [comment]
Hi @Peaj, do you mind sharing the code segment where you got this error?

**Comment by Peaj** [comment]
Hi @LeyangWen,

I just found that axis_interpretation is not part of this repository.
Sorry for the confusion.
Its part if the blender c3d importer using this module: https://github.com/MattiasFredriksson/io_anim_c3d
get and set_screen axis correctly assume the axis to be in string representation.
I will open an issue in the other repo.

Thanks,
Pascal
