### ISSUE TITLE
force plate data not aligned

### ISSUE THREAD

**Issue by dukeduck1984** [EmbodiedCognition/py-c3d#6]
Hi,

I tried to parse a c3d file from Kistler force plate and get the Fz1 data from it.  In V3D, Fz1 is the 3rd channel (starting from 1) and has 5 sub channels.  But when parsing with py-c3d, the 5 sub channels are analog[0, 2], [3, 0], [5, 3], [8, 1], [10, 4].  I had to reshape analog to (5, -1), so that I can get the 5 sub channels of Fz1 by analog[:, 2].

Is it a bug or did I do something wrong?  The c3d file attached.  The 13th channel is for the sync with EMG by the way.

Thanks.
Kaiyuan
[FP_CMJ_6.zip](https://github.com/EmbodiedCognition/py-c3d/files/1112632/FP_CMJ_6.zip)

**Comment by lmjohns3** [comment]
Looks like there's a potential solution for this issue in #7 -- please have a look, hopefully a PR is forthcoming.

**Comment by AKuederle** [comment]
@dukeduck1984 I created a pull request (#8) , that hopefully fixes your issue. I unfortunately can not test the change for a couple of days. It would be really great, if you can test if it fixes your issue :)
